name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build the Application
      run: npm run build

    - name: Archive Project
      run: |
        zip -r app.zip . -x "*.git*" "node_modules/*"

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_USER_NAME }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        source: "app.zip"
        target: "~/"
    - name: SSH and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_USER_NAME }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          sudo apt-get update -y
          sudo apt-get install unzip -y

          mkdir -p ~/app
          unzip -o ~/app.zip -d ~/app

          cd ~/app
          npm install --omit=dev
          npm run start

