name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build the Application
      run: npm run build

    - name: Run PM2 (Local to CI/CD Runner)
      run: |
        npm install -g pm2
        pm2 start dist/src/main.js
      continue-on-error: true

    - name: Deployment to EC2
      run: |
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        SSH_USER: ${{ secrets.SSH_USER }}
