name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

  # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm install

  # Step 4: Build the application
    - name: Build the Application
      run: npm run build


    - name: Deployment to EC2
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        echo "Changing to app directory..."
        
        echo "Installing production dependencies..."
        npm install 
        
        echo "Starting app..."
        npm start
        EOF

    
