name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build the Application
        run: npm run build

      - name: Deploy to EC2 via SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "Saving SSH key..."
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          echo "Preparing EC2 directory..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SSH_USER@$SSH_HOST << 'REMOTE'
            mkdir -p /home/$USER/mdm-service
            rm -rf /home/$USER/mdm-service/dist
          REMOTE

          echo "Copying build files to EC2..."
          scp -r -o StrictHostKeyChecking=no -i private_key.pem ./dist $SSH_USER@$SSH_HOST:/home/$SSH_USER/mdm-service/
          scp -r -o StrictHostKeyChecking=no -i private_key.pem ./package.json $SSH_USER@$SSH_HOST:/home/$SSH_USER/mdm-service/

          echo "Restarting app with PM2..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SSH_USER@$SSH_HOST << 'REMOTE'
            cd /home/$USER/mdm-service/src
            pm2 delete mdm-service || true
            pm2 start main.ts --name mdm-service
            pm2 save
          REMOTE

          echo "Deployment complete."
