name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build the Application
      run: npm run build

    - name: Archive Application Code
      run: |
        zip -r app.zip . -x "node_modules/*"

    - name: Deployment to EC2
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_USER: ${{ secrets.SSH_USER }}
        APP_DIR: "/var/www/my-node-app"
      run: |
        echo "Deploying to EC2 instance: $SSH_HOST"

        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        echo "Transferring app.zip to $SSH_USER@$SSH_HOST:$APP_DIR/"
        scp -o StrictHostKeyChecking=no app.zip "$SSH_USER@$SSH_HOST:$APP_DIR/"

        echo "Connecting to EC2 instance and deploying..."
        ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" << 'EOF'
          cd "$APP_DIR"

          echo "Stopping existing application..."
          pm2 stop all || true

          echo "Unzipping new application code..."
          unzip -o app.zip -d .

          echo "Installing production dependencies..."
          npm install --production

          echo "Starting new application..."
          pm2 start ecosystem.config.js || true
          pm2 save

          echo "Deployment complete!"
        EOF
