name: Node.js CI/CD - Simple

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Build the Application
      run: npm run build

    - name: Archive Build Artifacts
      run: |
        zip -r app_deploy_bundle.zip build/ package.json package-lock.json

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Transfer Build Artifacts to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "app_deploy_bundle.zip"
        target: "/tmp"

    - name: Deploy to EC2 and Restart App
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          APP_DIR="/home/${{ secrets.SSH_USER }}/mdm-service"
          mkdir -p $APP_DIR
          unzip -o /tmp/app_deploy_bundle.zip -d $APP_DIR
          rm /tmp/app_deploy_bundle.zip
          cd $APP_DIR
          npm ci --production
          npm start &
