name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build the Application
        run: npm run build

      - name: Deploy to EC2 via SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          echo "Saving SSH key..."
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          echo "Creating app directory on EC2..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SSH_USER@$SSH_HOST "mkdir -p /home/$SSH_USER/mdm-service"

          echo "Copying build files to EC2..."
          scp -o StrictHostKeyChecking=no -i private_key.pem -r ./dist $SSH_USER@$SSH_HOST:/home/$SSH_USER/mdm-service/

          echo "Creating .env file..."
          echo "MONGODB_URI=$MONGODB_URI" > .env

          echo "Uploading .env file to EC2 (inside dist/src)..."
          scp -o StrictHostKeyChecking=no -i private_key.pem .env $SSH_USER@$SSH_HOST:/home/$SSH_USER/mdm-service/dist/src/
          rm .env

          echo "Starting app with PM2..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SSH_USER@$SSH_HOST << 'EOF'
            cd /home/$SSH_USER/mdm-service/dist/src || exit 1
            pm2 describe mdm-service >/dev/null && pm2 delete mdm-service
            pm2 start main.js --name mdm-service
            pm2 save
          EOF

          rm -f private_key.pem
