name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

  
  # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm install

  # Step 4: Build the application
    - name: Build the Application
      run: npm run build

  # Step 5: Archive the build artifacts and node_modules using zip
    - name: Archive Build Artifacts and node_modules
      run: |
        zip -r build.zip .
        zip -r node_modules.zip node_modules/
        ls -lh node_modules.zip  # Debugging step to check if file is created
      continue-on-error: true

    - name: Deployment to EC2
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        SSH_USER: ${{ secrets.SSH_USER }}
        
      run: |
        cd ~/build.zip
        npm install
        npm start
        
