name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # or change to the branch you want

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Upload Artifact (App Zip)
      run: |
        zip -r app.zip .
        mkdir -p artifacts
        mv app.zip artifacts/

    - name: Upload Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: app-zip
        path: artifacts/app.zip

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: app-zip
        path: .

    - name: Deploy over SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        script: |
          sudo apt-get update -y
          sudo apt-get install unzip -y
          mkdir -p ~/app
          unzip -o ~/app.zip -d ~/app
          cd ~/app
          npm install --omit=dev
          npm run start
